sudo: required
services:
  - docker


before_install:
  - docker build -t "$DOCKER_ID"/test-react -f ./client/Dockerfile-dev .

script:
  - docker run "$DOCKER_ID"/test-react npm run test -- --coverage

after_success: 
  - docker built -t "$DOCKER_ID"/multi-client ./client   
  - docker built -t "$DOCKER_ID"/multi-server ./server
  - docker built -t "$DOCKER_ID"/multi-nginx ./nginx 
  - docker built -t "$DOCKER_ID"/multi-worker ./worker
  #overcome command line sequential login prompt 
  - echo "$DOCKER_PASSWORD" | docker login -u ""$DOCKER_ID"" --password-stdin
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-worker



# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "multi-container-docker-pipeline"
#   env: "DockerReactRedis-env"
#   bucket_name: "elasticbeanstalk-us-west-2-374863017875"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key:
#       secure: "$AWS_SECRET_KEY"
